
  service: aws-proj-2
  provider:
    name: aws
    runtime: nodejs18.x
    profile: serverlessUser
    stage: test
    region: "ap-south-1"
    vpc:
      securityGroupIds:
        - sg-095a3fecc0f89c707  # Replace with your actual security group ID
      subnetIds:
        - subnet-0c9b41fa52d04c553  # Replace with your actual subnet IDs
        - subnet-0ee113340a796323f
        - subnet-0a76e1f9041fd6e2a

  frameworkVersion: "3"
  plugins:
    - serverless-dotenv-plugin
    # - serverless-webpack
    - serverless-offline

  custom:
    webpack:
      webpackConfig: webpack.config.js

  layers:
    common-layer:
      arn: arn:aws:lambda:ap-south-1:381492152591:layer:common-layer:1


  package:
    individually: true


  functions:
    listProducts:
      handler: dist/app.handler
      events:
        - http:
            path: /api/product/list
            method: GET

    createProduct:
      handler: dist/app.handler
      events:
        - http:
            path: /api/product/create
            method: POST

    deleteProduct:
      handler: dist/app.handler
      events:
        - http:
            path: /api/product/remove/{id}
            method: DELETE

    updateProduct:
      handler: dist/app.handler
      events:
        - http:
            path: /api/product/update/{id}
            method: PUT

    getProduct:
      handler: dist/app.handler
      events:
        - http:
            path: /api/product/{id}
            method: GET


