
  service: aws-proj
  # app and org for use with dashboard.serverless.com
  #app: your-app-name
  #org: your-org-name

  # You can pin your service to only deploy with a specific Serverless version
  # Check out our docs for more details
  frameworkVersion: "3"

  provider:
    name: aws
    runtime: nodejs18.x
    profile: serverlessUser
    stage: test
    region: "ap-south-1"

  plugins:
    - serverless-dotenv-plugin
    - serverless-webpack
    - serverless-offline
  custom:
    webpack:
      webpackConfig: webpack.config.js


  package:
    individually: true
    # patterns:
    #   - './prisma'
    #   - '!node_modules/.prisma/client/libquery_engine-*'
    #   - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    #   - '!node_modules/prisma/libquery_engine-*'
    #   - '!node_modules/@prisma/engines/**'

  functions:
    register:
      handler: dist/app.handler
      events:
        - http:
            path: /api/user/register
            method: POST

    login:
      handler: dist/app.handler
      events:
        - http:
            path: /api/user/login
            method: POST

    logout:
      handler: dist/app.handler
      events:
        - http:
            path: /api/user/logout
            method: POST

    listUsers:
      handler: dist/app.handler
      events:
        - http:
            path: /api/user/list
            method: GET

    accessAcount:
      handler: dist/app.handler
      events:
        - http:
            path: /api/user/access
            method: POST

